import SubHeader from '@/components/subHeader'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'
import { usePathname } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="kr">
      <body className="w-full h-full  ">
        <main className="w-full  h-full max-w-[1200px] m-auto">{children}</main>
      </body>
    </html>
  )
}
